services:
    nginxx:
        container_name: nginxx
        build: ./nginxx
        image: nginxx
        volumes:
            - frontend_data:/usr/share/nginx/html
        ports:
            - "5050:5050"

volumes:
    frontend_data:
        driver: local
        driver_opts: 
            device: "./frontend/files"
            o: bind
            type: none

#networks:
    #app-network:
        #name: app-network
        #driver: bridge
        