services:
  node:
    container_name: node
    build: ./node
    image: node
    volumes:
      - ./node/res:/home/apriego-/node
      - node_data:/home/apriego-/node/res/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - pongnet
  login:
    container_name: login
    build: ./login
    image: login
    volumes:
      - login_data:/home/apriego-/login/
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - pongnet
    depends_on:
      - postgres
  tournament:
    container_name: tournament
    build: ./tournament
    command: python manage.py runserver 0.0.0.0:8000 #is this necessaryy ?
    volumes:
      - ./tournament/pong_back:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - pongnet
    depends_on:
      - login
    restart: 'always'
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6380:6379" #binding redis container 6379 to 6380 for machine as 42 uses this ports already
    networks:
      - pongnet
    restart: 'always'
    command: >
      sh -c "rm -f /data/dump.rdb && redis-server --save '' --appendonly no"
    #command: ["redis-server", "--save", "", "--appendonly", "no"]

  celery_worker:
    build: ./tournament
    container_name: celery_worker
    command: celery -A pong_project worker -l info
    env_file:
      - .env
    volumes:
      - ./tournament/pong_back:/app
    networks:
      - pongnet
    depends_on:
      - tournament
      - redis
    restart: 'always'

  celery_beat:
    build: ./tournament
    container_name: celery_beat
    command: celery -A pong_project beat -l info
    env_file:
      - .env
    volumes:
      - ./tournament/pong_back:/app
    networks:
      - pongnet
    depends_on:
      - tournament
      - redis
    restart: 'always'

  postgres:
    build: ./postgreSQL
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/home/apriego-/postgres
    ports:
      - "5432:5432"
    networks:
      - pongnet
volumes:
  node_data:
    driver: local
    driver_opts:
      device: "./node/res/node_modules"
      o: bind
      type: none
  login_data:
    driver: local
    driver_opts:
      device: "./login/res"
      o: bind
      type: none
  postgres_data:
    driver: local
    driver_opts:
      device: "./postgreSQL/res"
      o: bind
      type: none

networks:
  pongnet:
      name: pongnet
      driver: bridge
